### ISSUE TITLE
dub build step fails

### ISSUE THREAD

**Issue by dsobiera** [godot-dlang/godot-dlang#135]
**Describe the bug**
I am trying to get the environment set up. I get an error that fails the whole process on the dub build step for the README:

"Do a test build, dub build, you might see some warnings but that's ok"

../../../.dub/packages/godot-dlang/~master/godot-dlang/src/godot/api/reference.d(7,8):        Expected 'godot/refcounted.d' or 'godot/refcounted/package.d' in one of the following import paths:

I am running godot 4.1.2 on Ubuntu Linux 22.04.3.LTS and D v2.105.2.

Godot is at ~/bin/godot (Godot_v4.1.2-stable_mono_linux.x86_64 executable) and D is at ~/bin/dlang

**Comment by dsobiera** [comment]
A bit more text of the error:

../../../.dub/packages/godot-dlang/~master/godot-dlang/src/godot/api/reference.d(7,8):        Expected 'godot/refcounted.d' or 'godot/refcounted/package.d' in one of the following import paths:
import path[0] = ../../../.dub/packages/godot-dlang/~master/godot-dlang/src
import path[1] = ../../../.dub/packages/godot-dlang/~master/godot-dlang/classes
import path[2] = ../../../.dub/packages/godot-dlang/~master/godot-dlang/modules/util/
import path[3] = ../../../.dub/packages/utf_bc/0.2.1/utf_bc/source/
import path[4] = ~/bin/dlang/dmd-2.105.2/linux/bin64/../../src/phobos
import path[5] = ~/bin/dlang/dmd-2.105.2/linux/bin64/../../src/druntime/import
Error ~/bin/dlang/dmd-2.105.2/linux/bin64/dmd failed with exit code 1.

**Comment by Superbelko** [comment]
Did you run binding generator step?
https://github.com/godot-dlang/godot-dlang#generating-godot-bindings

**Comment by dsobiera** [comment]
I did run that binding step.  

Installing this I did via : dub add godot-dlang@~master

After reading your reply a few mins ago, I cloned the repo and checked out the godot-4.1 branch. My apologies for not doing this earlier.

So I assume I am in the "Manually building (advanced)" section of the README (except using godot-4.1 branch and not master like this section says).  But I'm not sure what this means:

"Use dub local project version lock file dub.selections.json to specify where to look for your local copy"

How will my new godot project's (that I am trying to use D with) dub.json know to use this branch? I'm thinking maybe this refers to this but am not quite getting it. Previously, I had in my dub.json:

	"dependencies": {
		"godot-dlang": "~master"
	},

But I did a "dub remove godot-dlang" to try to start over here.

Any assistance in helping me see what steps I am quite not getting would be much appreciated

**Comment by al1-ce** [comment]
Using "master" in dub is outdated and we probably do need to update readme in that

Also, to add path dependancy in dub (depending on your chosen format)
json:
```json
"dependencies": {
	  "godot-dlang": {
      "path": "path/to/package"
    } 
},
```

sdl:
```sdl
dependancy "godot-dlang" path="path/to/package" 
```

**Comment by dsobiera** [comment]
The bindings thing I did earlier created that .json file:

dsobiera:~/bin/godot$ pwd
/home/dsobiera/bin/godot
dsobiera:~/bin/godot$ ls -al
total 124192
drwxr-xr-x  3 dsobiera dsobiera      4096 Oct 13 10:33 .
drwxrwxr-x 13 dsobiera dsobiera      4096 Oct  8 10:49 ..
-rw-rw-r--  1 dsobiera dsobiera   5323172 Oct 13 10:17 extension_api.json
drwxr-xr-x  4 dsobiera dsobiera      4096 Oct  3 20:44 GodotSharp
-rwxr-xr-x  1 dsobiera dsobiera 121829760 Oct  4 05:02 Godot_v4.1.2-stable_mono_linux.x86_64


I cloned the repo to: /home/dsobiera/src/github/godot-dlang . I checkedout out godot-4.1

git status
On branch godot-4.1
Your branch is up to date with 'origin/godot-4.1'

I added this to my godot project's dub.json:

	"dependencies": {
		"godot-dlang": {
			"path": "/home/dsobiera/src/github/godot-dlang"
		}
	},

I get a variation of the original error but at least the path ../../github seem to point to my local copy

dub build
     Warning Invalid source/import path: /home/dsobiera/src/github/godot-dlang/classes
     Warning Invalid source/import path: /home/dsobiera/src/github/godot-dlang/classes
    Starting Performing "debug" build using /home/dsobiera/bin/dlang/dmd-2.105.2/linux/bin64/dmd for x86_64.
  Up-to-date godot-dlang:util 0.3.0+commit.15.gb09690f: target for configuration [library] is up to date.
  Up-to-date utf_bc 0.2.1: target for configuration [library] is up to date.
    Building godot-dlang 0.3.0+commit.15.gb09690f: building configuration [library]
    
    ...
    
    ../../github/godot-dlang/src/godot/api/reference.d(7,8): Error: unable to read module `refcounted`
../../github/godot-dlang/src/godot/api/reference.d(7,8):        Expected 'godot/refcounted.d' or 'godot/refcounted/package.d' in one of the following import paths:
import path[0] = ../../github/godot-dlang/src
import path[1] = ../../github/godot-dlang/classes
import path[2] = ../../github/godot-dlang/modules/util/
import path[3] = ../../../.dub/packages/utf_bc/0.2.1/utf_bc/source/
import path[4] = /home/dsobiera/bin/dlang/dmd-2.105.2/linux/bin64/../../src/phobos
import path[5] = /home/dsobiera/bin/dlang/dmd-2.105.2/linux/bin64/../../src/druntime/import
Error /home/dsobiera/bin/dlang/dmd-2.105.2/linux/bin64/dmd failed with exit code 1.

**Comment by al1-ce** [comment]
You need to run generator again since it puts classes into where godot-dlang package is located

**Comment by dsobiera** [comment]
Success.

Thank you!!!!

**Comment by al1-ce** [comment]
Cheers mate
