### ISSUE TITLE
Cannot build godot-dlang on Linux

### ISSUE THREAD

**Issue by chrisbare** [godot-dlang/godot-dlang#133]
```
**Describe the bug**
I am trying to get godot-dlang working with Godot 4.1.1 on linux but running into errors with the 0.3.0 release

**To Reproduce**
dub fetch godot-dlang
Godot_v4.1.1-stable_linux.x86_64 --dump-extension-api
dub run godot-dlang:generator -- -j extension_api.json -o
created a Godot project with the Godot editor
inside the project directory I ran: dub init d4-plugin
cd d4-plugin
edit dub.json and add the lines:
 "targetType": "dynamicLibrary",
	"dependencies": {
		"godot-dlang": "~>0.3.0"
	}
dub build
I get the following error:
../../.dub/packages/godot-dlang/0.3.0/godot-dlang/classes/godot/navigationmeshgenerator.d(83,173): Error: undefined identifier `Callable`
../../.dub/packages/godot-dlang/0.3.0/godot-dlang/classes/godot/navigationmeshgenerator.d(94,157): Error: undefined identifier `Callable`
../../.dub/packages/godot-dlang/0.3.0/godot-dlang/classes/godot/navigationserver3d.d(1324,173): Error: undefined identifier `Callable`
../../.dub/packages/godot-dlang/0.3.0/godot-dlang/classes/godot/navigationserver3d.d(1335,157): Error: undefined identifier `Callable`


**Expected behavior**
I expect dependencies to compile without error.

**Plaform (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
- DMD64 D Compiler v2.105.2
- DUB version 1.34.0, built on Sep 15 2023

I've used D and Godot a good bit separately, but I'm still not good with the intricacies of dub.
I also tried building from source by editing the dub.selections.json file and replacing:
		"godot-dlang": "0.3.0",
with 
  		"godot-dlang": "/oldroot/storage/src/godot-dlang",
but then dub build gives this error:
     Warning /home/chris/D4/d4-plugin/dub.selections.json(3:17): versions[godot-dlang]: Invalid SemVer format: /oldroot/storage/src/godot-dlang
    Starting Performing "debug" build using /usr/bin/dmd for x86_64.
    Building d4-plugin ~master: building configuration [library]
source/app.d(10,8): Error: unable to read module `godot`
source/app.d(10,8):        Expected 'godot.d' or 'godot/package.d' in one of the following import paths:
import path[0] = source/
import path[1] = /usr/include/dmd/phobos
import path[2] = /usr/include/dmd/druntime/import

I would like to contribute to this project, so in addition to helping me with this problem let me know where I could be helpful. I can write documentation, create examples or work on the actual godot-dlang code.
```

**Comment by al1-ce** [comment]
Last release is old
Try downloading master and using it instead

**Comment by al1-ce** [comment]
Also check godot-4.1 branch

**Comment by Superbelko** [comment]
4.1 is already supported and even has some critical fixes compared to last 4.0, try `godot-4.1` branch
https://github.com/godot-dlang/godot-dlang/tree/godot-4.1

There is also some very basic contributing guide, so check it out, and here is the document that explains a bit how godot-dlang works https://github.com/godot-dlang/godot-dlang-wiki/blob/master/006_Architecture-Overview.md

It is kind of suspended right now as we need to deal with this confusion, I'm waiting for godot 4.2 beta release so I can finally move master to an actual version.

**Comment by chrisbare** [comment]
Thanks I got it working with the 4.1 branch following the wiki. I'm going to update the wiki based on my experience.

**Comment by Superbelko** [comment]
Just tested out and `godot-4.1` seems to work with 4.2 dev6 too, so I think it can be used as is until a update bindings.

This problem seems to be resolved. Closing as fixed. Feel free to reopen if you still experience issues with it.
