### ISSUE TITLE
Does not compile with LDC 1.30.0 & VS Build Tools 2019

### ISSUE THREAD

**Issue by al1-ce** [godot-dlang/godot-dlang#1]
```
godot-d_util.lib(godotutil.classes.obj) : error LNK2019: unresolved external symbol _D3std4conv13ConvException7__ClassZ referenced in function _D3std4conv__T9convErrorTAxaTiZQrFNaNfQnAyamZCQBsQBr13ConvException
godot-d_util.lib(godotutil.classes.obj) : error LNK2019: unresolved external symbol _D3std4conv13ConvException6__vtblZ referenced in function _D3std4conv__T9convErrorTAxaTiZQrFNaNfQnAyamZCQBsQBr13ConvException
godot-d_util.lib(godotutil.classes.obj) : error LNK2019: unresolved external symbol _D3std4conv13ConvException6__initZ referenced in function _D3std4conv__T9convErrorTAxaTiZQrFNaNfQnAyamZCQBsQBr13ConvException
.dub\build\library-debug-windows-x86_64-ldc_v1.30.0-F48C6C820B5FF41BE10657ACA8512AD6\dlangtest.dll : fatal error LNK1120: 56 unresolved externals
Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe failed with status: 1120
ldc2 failed with exit code 1.
```

> oh ok, have a look at demo project dub.json, it has linker flags for some reason, could be related to that.
> "dflags-windows-ldc": ["-link-defaultlib-shared=false"],

**Comment by Superbelko** [comment]
It is getting worse, nor `"dflags-windows-ldc": ["-link-internally"]` neither `"dflags-windows-ldc": ["-link-defaultlib-shared=false"]` or even both no longer works for test/asteroids, failing on different modules with same reason - ModuleInfo unresolved symbol.

**Comment by al1-ce** [comment]
Does it work with dmd rn?

**Comment by Superbelko** [comment]
Yeah, it just LDC spitting random modules ModuleInfo, I just upgraded from LDC 1.28 and now this ...
Though LDC 1.30 works fine on linux, so Windows only issue.

**Comment by Superbelko** [comment]
Fixed with #93 

It also means that with great DLL support comes great DLL responsibility, so one have to __copy__ `druntime-ldc-shared.dll` and `phobos2-ldc-shared.dll` __next to__ `godot.exe`
