### ISSUE TITLE
This project doesn't build on Windows

### ISSUE THREAD

**Issue by ChrisG0x20** [godot-dlang/godot-dlang#107]
dub build fails:
----------------
> dub build
Invalid source/import path: ...\godot-dlang\classes
Invalid source/import path: ...\godot-dlang\classes
Performing "debug" build using C:\D\ldc2-1.25.1-windows-multilib\bin\ldc2.exe for x86_64.
godot-dlang 0.2.0+commit.1.g2caf362: building configuration "library"...
src\godot\api\reference.d(7,8): Error: module refcounted is in file 'godot\refcounted.d' which cannot be read
import path[0] = src
import path[1] = classes
import path[2] = modules\util
import path[3] = C:\Users\[username]\AppData\Local\dub\packages\utf_bc-0.2.1\utf_bc\source
import path[4] = C:\D\ldc2-1.25.1-windows-multilib\bin\..\import
C:\D\ldc2-1.25.1-windows-multilib\bin\ldc2.exe failed with exit code 1.

Extension generation fails:
---------------------------
> dub run godot-dlang:generator -- -j extension_api.json -o
Building package godot-dlang:generator in ...\godot-dlang\
Performing "debug" build using C:\D\ldc2-1.25.1-windows-multilib\bin\ldc2.exe for x86_64.
mir-core 1.5.3: target for configuration "library" is up to date.
mir-algorithm 3.20.1: building configuration "default"...
C:\Users\[username]\AppData\Local\dub\packages\mir-algorithm-3.20.1\mir-algorithm\source\mir\test.d(10,18): Error: undefined identifier noreturn
C:\D\ldc2-1.25.1-windows-multilib\bin\ldc2.exe failed with exit code 1.

Is this something that may be worked around?

**Comment by Superbelko** [comment]
missing import `classes` and `godot.refcounted` is generated bindings, did you run generator first?

Also note that minimum supported compiler version is 2.096 which is LDC 1.26, but I haven't tested below LDC 1.28 and DMD 2.099.

**Comment by ChrisG0x20** [comment]
I figured out that the version of LDC that comes with the Windows DMD install is too old. I've update LDC via chocolatey. It will now generate the bindings. However, I'm still missing the refcounted class.

The generator output:
> dub run godot-dlang:generator --force -- -j extension_api.json -o
             Building package godot-dlang:generator in C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-0.2.0\godot-dlang\
    Starting Performing "debug" build using C:\tools\ldc2-1.31.0-windows-multilib\bin\ldc2.exe for x86_64.
    Building mir-core 1.5.3: building configuration [library]
    Building mir-algorithm 3.20.1: building configuration [default]
    Building asdf 0.7.17: building configuration [library]
    Building dxml 0.4.3: building configuration [library]
    Building godot-dlang:util 0.2.0: building configuration [library]
    Building libdparse 0.20.0: building configuration [library]
    Building godot-dlang:generator 0.2.0: building configuration [application]
     Linking generator
     Running C:/Users/[username]/AppData/Local/dub/packages/godot-dlang-0.2.0/godot-dlang/generator.exe -j extension_api.json -o
["C:\\Users\\[username]\\AppData\\Local\\dub\\packages\\godot-dlang-0.2.0\\godot-dlang\\generator.exe"]
Outputting to default directory C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-0.2.0\godot-dlang\classes...
Overwriting existing output directory 'C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-0.2.0\godot-dlang\classes'...
Done! API bindings written to 'C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-0.2.0\godot-dlang\classes'


When I go to build my plugin in the godot directory I get this:
> dub build
     Warning WARNING: A deprecated branch based version specification is used for the dependency godot-dlang. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
     Warning Invalid source/import path: C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\classes
     Warning Invalid source/import path: C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\classes
    Starting Performing "debug" build using C:\tools\ldc2-1.31.0-windows-multilib\bin\ldc2.exe for x86_64.
  Up-to-date godot-dlang:util ~master: target for configuration [library] is up to date.
  Up-to-date utf_bc 0.2.1: target for configuration [library] is up to date.
    Building godot-dlang ~master: building configuration [library]
C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\src\godot\api\reference.d(7,8): Error: unable to read module `refcounted`
C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\src\godot\api\reference.d(7,8):        Expected 'godot\refcounted.d' or 'godot\refcounted\package.d' in one of the following import paths:
import path[0] = C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\src
import path[1] = C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\classes
import path[2] = C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\modules\util
import path[3] = C:\Users\[username]\AppData\Local\dub\packages\utf_bc-0.2.1\utf_bc\source
import path[4] = C:\tools\ldc2-1.31.0-windows-multilib\bin\..\import
Error C:\tools\ldc2-1.31.0-windows-multilib\bin\ldc2.exe failed with exit code 1.

**Comment by Superbelko** [comment]
>Expected 'godot\refcounted.d' or 'godot\refcounted\package.d' in one of the following import paths:
> import path[0] = C:\Users[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\src
> import path[1] = C:\Users[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang\classes

This, we had reports about this issue, when using package from dub the generator should by default output classes in that local dub cache folder but it didn't.

For now please manually copy them here ` C:\Users[username]\AppData\Local\dub\packages\godot-dlang-master\godot-dlang`
_(note for others: this path can be found by running dub list and searching for godot-dlang)_

**Comment by ChrisG0x20** [comment]
Ok. I found the file in: C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-0.2.0\godot-dlang\classes\godot\refcounted.d

Copied the folder C:\Users\[username]\AppData\Local\dub\packages\godot-dlang-0.2.0\godot-dlang\classes\godot
To my godot project folder: mygodotproject\dplugin\godot

`dub build` now completes with warnings about the incorrect import path, but I have a DLL.

Thank you.

**Comment by ChrisG0x20** [comment]
It builds now, however there are link errors for all the godot symbols. It appears to be ignoring the dub configuration: `"dflags-windows-ldc": ["-dllimport=defaultLibsOnly"]`

Any reference to a godot symbol produces a link error which prevents the DLL from being built. Is there a godot DLL that needs to be copied into the plugin directory?

**Comment by Superbelko** [comment]
This is LDC specific issue when dealing with D DLL's on Windows. 
It looks like LDC thinks godot-dlang itself is dynamic library.

Without thorough investigation I can only think of 
1) `classes` absolutely must be placed in godot-dlang root path
2) LDC needs flag `-fvisibility=hidden` 
3) ???

**Comment by Superbelko** [comment]
I forgot to mention that even though you might have LDC in %PATH% you still need its runtime DLL's it in some known location, for my needs I simply put `druntime-ldc-shared.dll` and `phobos2-ldc-shared.dll` next to godot.exe.

Also on Linux it is done by setting LD_LIBRARY_PATH (DLL search paths env variable) in a helper script that starts your godot game, godot itself AFAIK doesn't have any special flags or env variables for that.

**Comment by ChrisG0x20** [comment]
Thanks. Ha! I'm sure that one would have gotten me at some point too.

**Comment by ChrisG0x20** [comment]
@Superbelko You were correct again. The reason LoadLibrary() was failing was not because it couldn't fine the plugin DLL, it was because of the druntime DLLs that aren't available with godot's default search path.
