### ISSUE TITLE
Cannot build a project on mac

### ISSUE THREAD

**Issue by stan220** [godot-dlang/godot-dlang#212]
HI! Could you help me? I Create a project by using init script:

`dub run godot-dlang:init`

Project successfully initialized.

```
(dmd-2.109.1) 12:20:49 ~/stan/ddd $ dub build

    Starting Performing "debug" build using /Users/user/dlang/dmd-2.109.1/osx/bin/dmd for x86_64.

  Up-to-date godot-dlang:util 0.7.0: target for configuration [library] is up to date.

  Up-to-date utf_bc 0.2.1: target for configuration [library] is up to date.

    Building godot-dlang 0.7.0: building configuration [default]

   Pre-build Running commands

../../.dub/packages/godot-dlang/0.7.0/godot-dlang/classes/godot/builtins.d(9947,15): Error: unable to read module `packedvector4array`

../../.dub/packages/godot-dlang/0.7.0/godot-dlang/classes/godot/builtins.d(9947,15):        Expected 'godot/packedvector4array.d' or 'godot/packedvector4array/package.d' in one of the following import paths:

import path[0] = ../../.dub/packages/godot-dlang/0.7.0/godot-dlang/src

import path[1] = ../../.dub/packages/godot-dlang/0.7.0/godot-dlang/classes

import path[2] = ../../.dub/packages/godot-dlang/0.7.0/godot-dlang/modules/util/

import path[3] = ../../.dub/packages/utf_bc/0.2.1/utf_bc/source/

import path[4] = /Users/user/dlang/dmd-2.109.1/osx/bin/../../src/phobos

import path[5] = /Users/user/dlang/dmd-2.109.1/osx/bin/../../src/druntime/import

Error /Users/user/dlang/dmd-2.109.1/osx/bin/dmd failed with exit code 1.
```

**Comment by Superbelko** [comment]
Can you build asteroids example to see if it is working? If so, it could be init script that has not been updated for quite some time.

**Comment by Superbelko** [comment]
closing as completed.

just a little context, when i was messing up with binding generator the IDE sometimes automatically adds unwanted imports, importing anything outside generator and util packages will silently introduce cyclic dependency, e.g. not be able to generate bindings <-> no such imports without bindings.

anyway since v0.8 is now live it should work fine.
